services:
  scraper-api:
    build: .
    image: moamen1358/website-scrapper:latest
    container_name: scraper-api
    ports:
      - "8000:8000"
    volumes:
      - ./config:/app/config
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - SCRAPER_HEADLESS=true
      - SCRAPER_PROXY_ENABLED=false
      - SCRAPER_CAPTCHA_ENABLED=false
    restart: unless-stopped
